version: "3"

dotenv: [".build.env"]

tasks:
  build-debug:
    desc: Build with debug symbols for the current platform.
    summary: |
      Build with debug symbols for the current platform.
    cmds:
      - go build -gcflags "all=-N -l" -o ./out/debug/bashy ./src

    generates:
      - ./out/debug/bashy
      

  build-linux:
    desc: Build for Linux.
    summary: |
      Build for Linux.
    cmds:
      -  env GOOS=linux go build    --ldflags '-extldflags "-static"' -o ./out/bashy.linux ./src
    generates:
      - out/bashy.linux
  build-windows:
    desc: Build for Linux.
    summary: |
      Build for Linux.
    cmds:
      -  env GOOS=windows go build     -o ./out/bashy.windows ./src

    generates:
      - out/bashy.windows

  clean:
    desc: Clean temp artifacts.
    summary: |
      Clean temp artifacts.
    srcs:
      - rm -rf out

  run:
    desc: Run app on current platform.
    summary: |
      Run the application
    cmds:
      - go run ./src/main.go
 
  test:
    desc: Run all tests.
    summary: |
      Run all tests.
    srcs:
      - go test ./...
