version: "3"

dotenv: [".build.env"]

tasks:
  build-debug:
    desc: Build with debug symbols for the current platform.
    summary: |
      Build with debug symbols for the current platform.
    srcs:
      - go build -gcflags "all=-N -l" -o ./tmp/__debug_bin ./src
    sources:
      - src/**/*.go
      - src/main.go
    generates:
      - tmp/__debug_bin

  build-linux:
    desc: Build for Linux.
    summary: |
      Build for Linux.
    srcs:
      -  go build -gcflags "all=-N -l" -o ./bin/linux/bashy ./src
    # sources:
    #   - src/**/*.go
    #   - src/main.go
    generates:
      - bin/linux/bashy
    vars:
      DOCKER_IMAGE: frontend_image

  clean:
    desc: Clean temp artifacts.
    summary: |
      Clean temp artifacts.
    srcs:
      - go run ./scripts/clean

  run:
    desc: Run app on current platform.
    summary: |
      Run the application
    cmds:
      - go run ./src/main.go
 
  test:
    desc: Run all tests.
    summary: |
      Run all tests.
    srcs:
      - go test ./...
