# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Output Step'
      env:
        NEW_TAG: ${{ steps.tag_version.outputs.new_tag }}
      run: echo "new tag $NEW_TAG"
    - uses: ClementTsang/delete-tag-and-release@v0.3.1
      with:
        delete_release: false
        tag_name: latets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: rickstaa/action-create-tag@v1
      with:
        tag: "latest"
        message: "Latest release"
        no_verify_tag: true
        force_push_tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: install task
      run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      shell: bash
      
    - name: Build for linux
      run: bin/task build-linux
      shell: bash
    - name: Build for windows
      run: bin/task build-windows
      shell: bash
      
    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NEW_TAG: ${{ steps.tag_version.outputs.new_tag }}
        NAME: Release ${{ steps.tag_version.outputs.new_tag }}
        CHANGELOG: ${{ steps.tag_version.outputs.changelog }}
      shell: bash
      run: |
        TITLE='Latest'
        BODY='Test release'
        go install github.com/tcnksm/ghr         
        ghr -n="$NAME" -b="$CHANGELOG"   $NEW_TAG ./out/
        ghr -n="$TITLE" -b="$BODY" -delete  latest ./out/

