# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: install task
      run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
      shell: bash
      
    - name: Build for linux
      run: bin/task build-linux
      shell: bash
    - name: Build for windows
      run: bin/task build-windows
      shell: bash
      
    - name: Publish
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        TITLE='Latest'
        BODY='Test release'
        go install github.com/tcnksm/ghr 
        ghr -n $TITLE -b $BODY -delete  latest ./out/

